export const styles = {
  page: { fontFamily: 'Arial, sans-serif', background: '#f4f7fb', minHeight: '100vh', padding: 16, color: '#1f2937' } as const,
  shell: { maxWidth: 1400, margin: '0 auto' } as const,
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16, marginBottom: 16, flexWrap: 'wrap' } as const,
  titleWrap: { display: 'flex', flexDirection: 'column', gap: 4 } as const,
  title: { margin: 0, fontSize: 30, fontWeight: 700 } as const,
  subtitle: { margin: 0, color: '#4b5563', fontSize: 14 } as const,
  buttonRow: { display: 'flex', gap: 10, flexWrap: 'wrap' } as const,
  card: { background: 'white', border: '1px solid #dbe3ee', borderRadius: 14, boxShadow: '0 4px 14px rgba(0,0,0,0.05)', padding: 18 } as const,
  grid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18 } as const,
  leftCol: { display: 'grid', gap: 18, alignSelf: 'start' } as const,
  rightCol: { display: 'grid', gap: 18, alignSelf: 'start' } as const,
  sectionTitle: { fontSize: 20, fontWeight: 700, marginBottom: 12 } as const,
  smallTitle: { fontSize: 16, fontWeight: 700, marginBottom: 8 } as const,
  label: { fontWeight: 700, marginBottom: 6, display: 'block', fontSize: 14 } as const,
  input: { width: '100%', padding: 10, borderRadius: 8, border: '1px solid #cbd5e1', fontSize: 15, boxSizing: 'border-box' as const, background: 'white' },
  textarea: { width: '100%', padding: 10, borderRadius: 8, border: '1px solid #cbd5e1', fontSize: 15, boxSizing: 'border-box' as const, background: 'white', resize: 'vertical' as const },
  select: { width: '100%', padding: 10, borderRadius: 8, border: '1px solid #cbd5e1', fontSize: 15, background: 'white' },
  primaryBtn: { padding: '10px 14px', borderRadius: 8, border: 'none', cursor: 'pointer', background: '#2563eb', color: 'white', fontWeight: 600 } as const,
  secondaryBtn: { padding: '10px 14px', borderRadius: 8, border: '1px solid #cbd5e1', cursor: 'pointer', background: 'white', color: '#111827', fontWeight: 600 } as const,
  mutedBtn: { padding: '10px 14px', borderRadius: 8, border: 'none', cursor: 'pointer', background: '#64748b', color: 'white', fontWeight: 600 } as const,
  successBtn: { padding: '10px 14px', borderRadius: 8, border: 'none', cursor: 'pointer', background: '#15803d', color: 'white', fontWeight: 600 } as const,
  dangerBtn: { padding: '10px 14px', borderRadius: 8, border: 'none', cursor: 'pointer', background: '#b91c1c', color: 'white', fontWeight: 600 } as const,
  amberBtn: { padding: '10px 14px', borderRadius: 8, border: 'none', cursor: 'pointer', background: '#a16207', color: 'white', fontWeight: 600 } as const,
  badge: { display: 'inline-block', padding: '6px 10px', background: '#eef2ff', color: '#3730a3', borderRadius: 999, fontSize: 13, fontWeight: 700 } as const,
  infoBox: { border: '1px solid #dbe3ee', borderRadius: 10, padding: 12, background: '#f8fafc', lineHeight: 1.65 } as const,
  prayerViewer: { fontSize: 28, lineHeight: 1.8, border: '1px solid #dbe3ee', borderRadius: 10, padding: 18, minHeight: 220, background: '#fff' } as const,
  seqItem: { border: '1px solid #dbe3ee', borderRadius: 10, padding: 12, background: '#fbfdff' } as const,
  menuCard: { background: '#ffffff', border: '1px solid #dbe3ee', borderRadius: 14, boxShadow: '0 4px 14px rgba(0,0,0,0.05)', padding: 14 } as const,
  topBar: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 12, marginBottom: 16, flexWrap: 'wrap' } as const,
};
